#pragma checksum "E:\Source\Github\Liquidboy\X\src\X.Store.UWP\Store.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "7BA6BAF3F4C0EADDA8651F3AFB903B18"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.Store.UWP
{
    partial class Store : global::Windows.UI.Xaml.Controls.UserControl
    {


        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.DataTemplate dtMovie; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.DataTemplate dtTV; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.DataTemplate dtSimilarMovie; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Grid layoutRoot; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.GridView grdItems; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Grid grdDetails; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Grid grdTrailer; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Grid grdDownload; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.MediaElement meDownload; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Button butResizeDownload; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Button butCloseDownload; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.MediaElement meTrailer; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Button butResizeTrailer; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Button butCloseTrailer; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.ListView grdSimilarItems; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Button butCloseDetails; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Button butWatchTrailer; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Button butWatch; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Button butMovies; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private global::Windows.UI.Xaml.Controls.Button butShows; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        private bool _contentLoaded;

        /// <summary>
        /// InitializeComponent()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent()
        {
            if (_contentLoaded)
                return;

            _contentLoaded = true;

            global::System.Uri resourceLocator = new global::System.Uri("ms-appx:///X.Store.UWP/Store.xaml");
            global::Windows.UI.Xaml.Application.LoadComponent(this, resourceLocator, global::Windows.UI.Xaml.Controls.Primitives.ComponentResourceLocation.Nested);
        }

        partial void UnloadObject(global::Windows.UI.Xaml.DependencyObject unloadableObject);

    }
}


