#pragma checksum "E:\Source\Github\Liquidboy\X\src\X.Store.UWP\Store.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "B053C8652E794A8F9F026242DD1B003E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.Store.UWP
{
    partial class Store : 
        global::Windows.UI.Xaml.Controls.UserControl, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 2: // Store.xaml line 12
                {
                    this.dtMovie = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 3: // Store.xaml line 19
                {
                    this.dtTV = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 4: // Store.xaml line 26
                {
                    this.dtSimilarMovie = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 8: // Store.xaml line 32
                {
                    this.layoutRoot = (global::Windows.UI.Xaml.Controls.Grid)(target);
                    ((global::Windows.UI.Xaml.Controls.Grid)this.layoutRoot).Loaded += this.LayoutRoot_Loaded;
                }
                break;
            case 9: // Store.xaml line 37
                {
                    this.grdItems = (global::Windows.UI.Xaml.Controls.GridView)(target);
                    ((global::Windows.UI.Xaml.Controls.GridView)this.grdItems).SelectionChanged += this.GrdItems_SelectionChanged;
                }
                break;
            case 10: // Store.xaml line 39
                {
                    this.grdDetails = (global::Windows.UI.Xaml.Controls.Grid)(target);
                }
                break;
            case 11: // Store.xaml line 66
                {
                    this.grdTrailer = (global::Windows.UI.Xaml.Controls.Grid)(target);
                }
                break;
            case 12: // Store.xaml line 68
                {
                    this.meTrailer = (global::Windows.UI.Xaml.Controls.MediaElement)(target);
                }
                break;
            case 13: // Store.xaml line 69
                {
                    this.butResizeTrailer = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butResizeTrailer).Click += this.ButResizeTrailer_Click;
                }
                break;
            case 14: // Store.xaml line 70
                {
                    this.butCloseTrailer = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butCloseTrailer).Click += this.ButCloseTrailer_Click;
                }
                break;
            case 15: // Store.xaml line 56
                {
                    this.grdSimilarItems = (global::Windows.UI.Xaml.Controls.ListView)(target);
                }
                break;
            case 16: // Store.xaml line 49
                {
                    this.butCloseDetails = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butCloseDetails).Click += this.ButCloseDetails_Click;
                }
                break;
            case 17: // Store.xaml line 51
                {
                    this.butWatchTrailer = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butWatchTrailer).Click += this.ButWatchTrailer_Click;
                }
                break;
            case 18: // Store.xaml line 52
                {
                    this.butWatch = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butWatch).Click += this.ButWatch_Click;
                }
                break;
            case 19: // Store.xaml line 34
                {
                    this.butMovies = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butMovies).Click += this.ButMovies_Click;
                }
                break;
            case 20: // Store.xaml line 35
                {
                    this.butShows = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butShows).Click += this.ButShows_Click;
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18309.1000")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

