// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.Storage.Streams.1.h"
#include "winrt/impl/Windows.UI.Composition.1.h"
#include "winrt/impl/Windows.UI.Composition.Scenes.1.h"
#include "winrt/impl/SceneLoaderComponent.1.h"

WINRT_EXPORT namespace winrt::SceneLoaderComponent {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::SceneLoaderComponent {

struct WINRT_EBO SceneLoader :
    SceneLoaderComponent::ISceneLoader
{
    SceneLoader(std::nullptr_t) noexcept {}
    SceneLoader();
};

}
