// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190321.3

#ifndef WINRT_SceneLoaderComponent_2_H
#define WINRT_SceneLoaderComponent_2_H
#include "winrt/impl/SceneLoaderComponent.1.h"
namespace winrt::SceneLoaderComponent
{
    struct WINRT_EBO SceneLoader : SceneLoaderComponent::ISceneLoader
    {
        SceneLoader(std::nullptr_t) noexcept {}
        SceneLoader(void* ptr, take_ownership_from_abi_t) noexcept : SceneLoaderComponent::ISceneLoader(ptr, take_ownership_from_abi) {}
        SceneLoader();
    };
}
#endif
