// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190321.3

#ifndef WINRT_SceneLoaderComponent_1_H
#define WINRT_SceneLoaderComponent_1_H
#include "winrt/impl/SceneLoaderComponent.0.h"
namespace winrt::SceneLoaderComponent
{
    struct WINRT_EBO ISceneLoader :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISceneLoader>
    {
        ISceneLoader(std::nullptr_t = nullptr) noexcept {}
        ISceneLoader(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
