// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.Storage.Streams.0.h"
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Composition.Scenes.0.h"
#include "winrt/impl/SceneLoaderComponent.0.h"

WINRT_EXPORT namespace winrt::SceneLoaderComponent {

struct WINRT_EBO ISceneLoader :
    Windows::Foundation::IInspectable,
    impl::consume_t<ISceneLoader>
{
    ISceneLoader(std::nullptr_t = nullptr) noexcept {}
};

}
