// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Graphics.DirectX.h"
#include "winrt/Windows.Storage.h"
#include "winrt/Windows.UI.Composition.h"
#include "winrt/Microsoft.UI.Composition.Toolkit.h"

namespace winrt::Microsoft::UI::Composition::Toolkit::implementation {

template <typename D, typename ... I>
struct WINRT_EBO CompositionImageOptions_base : impl::module_lock, implements<D, Microsoft::UI::Composition::Toolkit::ICompositionImageOptions, I ...>
{
    using class_type = Microsoft::UI::Composition::Toolkit::CompositionImageOptions;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename D::first_interface, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Microsoft.UI.Composition.Toolkit.CompositionImageOptions";
    }
};

}

namespace winrt::Microsoft::UI::Composition::Toolkit::factory_implementation {

template <typename D, typename T, typename ... I>
struct WINRT_EBO CompositionImageOptionsT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Microsoft.UI.Composition.Toolkit.CompositionImageOptions";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_COMPOSITIONIMAGEOPTIONS_XAML_G_H) || __has_include("CompositionImageOptions.xaml.g.h")

#include "CompositionImageOptions.xaml.g.h"

#else

namespace winrt::Microsoft::UI::Composition::Toolkit::implementation
{
    template <typename D, typename ... I>
    using CompositionImageOptionsT = CompositionImageOptions_base<D, I ...>;
}

#endif
