#pragma checksum "E:\Source\Github\Liquidboy\X\src\X.Store.UWP\Store.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "15706D009B5A4836BE25FA60CE953975"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X.Store.UWP
{
    partial class Store : 
        global::Windows.UI.Xaml.Controls.UserControl, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18334.1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 2: // Store.xaml line 177
                {
                    this.dtMovie = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 3: // Store.xaml line 184
                {
                    this.dtTV = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 4: // Store.xaml line 191
                {
                    this.dtSimilarMovie = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 5: // Store.xaml line 196
                {
                    this.dtEpisode = (global::Windows.UI.Xaml.DataTemplate)(target);
                }
                break;
            case 7: // Store.xaml line 218
                {
                    global::Windows.UI.Xaml.Controls.Button element7 = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)element7).Click += this.ButWatchEpisode_Click;
                }
                break;
            case 25: // Store.xaml line 222
                {
                    this.layoutRoot = (global::Windows.UI.Xaml.Controls.Grid)(target);
                    ((global::Windows.UI.Xaml.Controls.Grid)this.layoutRoot).Loaded += this.LayoutRoot_Loaded;
                }
                break;
            case 26: // Store.xaml line 227
                {
                    this.grdItems = (global::Windows.UI.Xaml.Controls.GridView)(target);
                    ((global::Windows.UI.Xaml.Controls.GridView)this.grdItems).SelectionChanged += this.GrdItems_SelectionChanged;
                }
                break;
            case 27: // Store.xaml line 229
                {
                    this.grdDetailsMovie = (global::Windows.UI.Xaml.Controls.Grid)(target);
                }
                break;
            case 28: // Store.xaml line 272
                {
                    this.grdDetailsShow = (global::Windows.UI.Xaml.Controls.Grid)(target);
                }
                break;
            case 29: // Store.xaml line 302
                {
                    this.grdTrailer = (global::Windows.UI.Xaml.Controls.Grid)(target);
                }
                break;
            case 30: // Store.xaml line 309
                {
                    this.grdDownload = (global::Windows.UI.Xaml.Controls.Grid)(target);
                }
                break;
            case 31: // Store.xaml line 311
                {
                    this.meDownload = (global::Windows.UI.Xaml.Controls.MediaElement)(target);
                }
                break;
            case 32: // Store.xaml line 313
                {
                    this.downloadItems = (global::Windows.UI.Xaml.Controls.ItemsControl)(target);
                }
                break;
            case 33: // Store.xaml line 335
                {
                    this.butResizeDownload = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butResizeDownload).Click += this.ButResizeDownload_Click;
                }
                break;
            case 34: // Store.xaml line 336
                {
                    this.butPlayDownload = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butPlayDownload).Click += this.ButPlayDownload_Click;
                }
                break;
            case 35: // Store.xaml line 337
                {
                    this.butCloseDownload = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butCloseDownload).Click += this.ButCloseDownload_Click;
                }
                break;
            case 37: // Store.xaml line 304
                {
                    this.meTrailer = (global::Windows.UI.Xaml.Controls.MediaElement)(target);
                }
                break;
            case 38: // Store.xaml line 305
                {
                    this.butResizeTrailer = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butResizeTrailer).Click += this.ButResizeTrailer_Click;
                }
                break;
            case 39: // Store.xaml line 306
                {
                    this.butCloseTrailer = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butCloseTrailer).Click += this.ButCloseTrailer_Click;
                }
                break;
            case 40: // Store.xaml line 291
                {
                    this.grdEpisodes = (global::Windows.UI.Xaml.Controls.ListView)(target);
                }
                break;
            case 41: // Store.xaml line 282
                {
                    this.butCloseDetailsShow = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butCloseDetailsShow).Click += this.ButCloseDetails_Click;
                }
                break;
            case 42: // Store.xaml line 284
                {
                    this.butWatchTrailerShow = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butWatchTrailerShow).Click += this.ButWatchTrailer_Click;
                }
                break;
            case 43: // Store.xaml line 264
                {
                    this.grdSimilarItemsMovie = (global::Windows.UI.Xaml.Controls.ListView)(target);
                    ((global::Windows.UI.Xaml.Controls.ListView)this.grdSimilarItemsMovie).ItemClick += this.GrdSimilarItemsMovie_ItemClick;
                }
                break;
            case 44: // Store.xaml line 257
                {
                    this.butCloseDetailsMovie = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butCloseDetailsMovie).Click += this.ButCloseDetails_Click;
                }
                break;
            case 45: // Store.xaml line 259
                {
                    this.butWatchTrailerMovie = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butWatchTrailerMovie).Click += this.ButWatchTrailer_Click;
                }
                break;
            case 46: // Store.xaml line 260
                {
                    this.butWatchMovie = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butWatchMovie).Click += this.ButWatchMovie_Click;
                }
                break;
            case 48: // Store.xaml line 224
                {
                    this.butMovies = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butMovies).Click += this.ButMovies_Click;
                }
                break;
            case 49: // Store.xaml line 225
                {
                    this.butShows = (global::Windows.UI.Xaml.Controls.Button)(target);
                    ((global::Windows.UI.Xaml.Controls.Button)this.butShows).Click += this.ButShows_Click;
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 10.0.18334.1")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

