using CoreLib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace X.Extensions.ThirdParty
{
    public static class Installer
    {
        public static List<ExtensionManifest> GetExtensionManifests() {
            var extensions = new List<ExtensionManifest>();
            
            extensions.Add(new ExtensionManifest("zoo", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/zoo/zoo.png", "Sample Extensions", "1.0", "zoo details", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Bottom) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Stitcher", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Stitcher/Stitcher.png", "Sample Extensions", "1.0", "Stitcher xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Bottom) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Spotify", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Spotify/Spotify.png", "Sample Extensions", "1.0", " Spotify xxxx", ExtensionInToolbarPositions.Bottom, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Pixta", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Pixta/Pixta.png", "Sample Extensions", "1.0", "Pixta xxxx", ExtensionInToolbarPositions.Bottom, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("F12", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/F12/F12.png", "Sample Extensions", "1.0", "f12 xxxxx", ExtensionInToolbarPositions.Bottom, ExtensionInToolbarPositions.BottomFull) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Songist", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Songist/Songist.png", "Sample Extensions", "1.0", "Songist xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Right) { IsExtEnabled = false });
            //extensions.Add(new SmartHeader()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new SecureShell()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new Quant()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            extensions.Add(new ExtensionManifest("Plex", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Plex/Plex.png", "Sample Extensions", "1.0", "Plex xxxx ", ExtensionInToolbarPositions.Bottom, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("LastPass", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/LastPass/LastPass.png", "Sample Extensions", "1.0", "LastPass xxxx", ExtensionInToolbarPositions.Bottom, ExtensionInToolbarPositions.Bottom) { IsExtEnabled = false });
            //extensions.Add(new Koding()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new HistoryEraser()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new Feedly()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            extensions.Add(new ExtensionManifest("Duo Lingo", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/DuoLingo/DuoLingo.png", "Sample Extensions", "1.0", "DuoLingo language service", ExtensionInToolbarPositions.Left, ExtensionInToolbarPositions.Bottom) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Adblocker Plus", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/ABP/abp.png", "Sample Extensions", "1.0", "Block adverts in the page", ExtensionInToolbarPositions.Top | ExtensionInToolbarPositions.Left, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Advanced Rest Client", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/AdvancedRestClient/AdvancedRestClient.png", "Sample Extensions", "1.0", "A rest client for testing rest services", ExtensionInToolbarPositions.Top | ExtensionInToolbarPositions.Right, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Assistant To", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/AssistantTo/AssistantTo.png", "Sample Extensions", "1.0", "personal assistant for managing your web browsing habits", ExtensionInToolbarPositions.Right, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Black Menu", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/BlackMenu/BlackMenu.png", "Sample Extensions", "1.0", "List of Google services served up in a black menu", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Color Hexa", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/ColorHexa/ColorHexa.png", "Sample Extensions", "1.0", "Configure Color Hex values for the selected site", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Draw IO", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/DrawIO/DrawIO.png", "Sample Extensions", "1.0", "Sample Drawing extension", ExtensionInToolbarPositions.Right, ExtensionInToolbarPositions.Right) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("DuckDuckGo", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/DuckDuckGo/DuckDuckGo.png", "Sample Extensions", "1.0", "Search engine duck duck go ...", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("AwesomeScreenshot", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/AwesomeScreenshot/AwesomeScreenshot.png", "Sample Extensions", "1.0", "take great screenshots of any website", ExtensionInToolbarPositions.Bottom, ExtensionInToolbarPositions.Right) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Google Hangouts", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/GoogleHangouts/GoogleHangouts.png", "Community chat boards", "1.0", "xxxx", ExtensionInToolbarPositions.Right, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Chrometana", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Chrometana/Chrometana.png", "Sample Extensions", "1.0", "Cortana as a google nacl extension", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Google Keep", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/GoogleKeep/GoogleKeep.png", "Sample Extensions", "1.0", "Keep your personal information safe from Googles searches", ExtensionInToolbarPositions.Right, ExtensionInToolbarPositions.Bottom) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Html Fire", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/HtmlFire/HtmlFire.png", "Sample Extensions", "1.0", "Quickly optimize HTMl within a chosen website", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Little Alchemy", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/LittleAlchemy/LittleAlchemy.png", "Sample Extensions", "1.0", "Cool little game", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Nitrous", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Nitrous/Nitrous.png", "Sample Extensions", "1.0", "Nitrous game engine", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Right) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("OneNote", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/OneNote/OneNote.png", "Sample Extensions", "1.0", "Microsoft Office OneNote", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Right) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("ooVoo", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/ooVoo/ooVoo.png", "Sample Extensions", "1.0", "ooVoo video player", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Top) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Padlet", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Padlet/Padlet.png", "Sample Extensions", "1.0", "Playing with colors , schemes and themes", ExtensionInToolbarPositions.Bottom, ExtensionInToolbarPositions.Top) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Pixlr", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Pixlr/Pixlr.png", "Sample Extensions", "1.0", "Pixlr the pixel manipulation tool", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Right) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("Polarr", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Polarr/Polarr.png", "Sample Extensions", "1.0", "Polarize your image", ExtensionInToolbarPositions.Bottom, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            extensions.Add(new ExtensionManifest("RatingsPreview", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/RatingsPreview/RatingsPreview.png", "Sample Extensions", "1.0", "View your Youtubes ratings and review them...", ExtensionInToolbarPositions.Right, ExtensionInToolbarPositions.Bottom) { IsExtEnabled = false });
            //extensions.Add(new Rdio()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new SessionBuddy()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new SketchboardIO()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new Storybird()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            extensions.Add(new ExtensionManifest("Teamviewer", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/Teamviewer/Teamviewer.png", "Sample Extensions", "1.0", "Teamviewer vpn access to all your devices", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left) { IsExtEnabled = false });
            //extensions.Add(new Twerk()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new WordOnline()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new WorkFlowy()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));
            //extensions.Add(new wunderlist()); _Template(new ExtensionManifest("xxxx", "ms-appx:///X.Extensions.ThirdParty/Assets/Extensions/ThirdParty/xxxx/xxxx.png", "Sample Extensions", "1.0", "xxxx", ExtensionInToolbarPositions.Top, ExtensionInToolbarPositions.Left));


            return extensions;
        }
    }
}
